add_rules("mode.debug", "mode.release")

set_configdir("qt","~/Qt/6.2.4/gcc_64")
toolchain("my_toolchain")
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang", "clang++")
toolchain_end()
set_toolchains("my_toolchain")
add_includedirs("~/Qt/6.2.4/gcc_64/include")

-- add_frameworks("QtCore")
-- add_frameworks("QtGui")
-- add_frameworks("QtQml")
-- add_frameworks("QtQuick")
add_frameworks("QtQuick3D")
add_frameworks("QtDataVisualization")
add_frameworks("QtSql")
add_frameworks("QtQuickControls2")
add_frameworks("QtMultimedia")


-- multimedia
target("declarative-camera")
    add_rules("qt.quickapp")
    add_files("multimedia/declarative-camera/qml.qrc")
    add_files("multimedia/declarative-camera/*.cpp")
    -- add_files("multimedia/declarative-camera/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("video_mediaplayer")
    add_rules("qt.quickapp")
    add_files("multimedia/video/mediaplayer/qml.qrc")
    add_files("multimedia/video/mediaplayer/*.cpp")
    -- add_files("multimedia/video/mediaplayer/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("video_qmlvideo")
    add_rules("qt.quickapp")
    add_files("multimedia/video/qmlvideo/qml.qrc")
    add_files("multimedia/video/qmlvideo/*.cpp",{rule = "qt.moc"})
    add_files("multimedia/video/qmlvideo/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
    
    -- add_includedirs("")
target("video_recorder")
    add_rules("qt.quickapp")
    add_files("multimedia/video/recorder/qml.qrc")
    add_files("multimedia/video/recorder/*.cpp")
    -- add_files("multimedia/video/recorder/*.h")-- add files with Q_OBJECT meta (only for qt.moc)

-- add_rules("qt.qmlplugin")
-- set_values("qt.qmlplugin.import_name", "My.Plugin")
