add_rules("mode.debug", "mode.release")
set_configdir("qt","~/Qt/6.2.4/gcc_64")
toolchain("my_toolchain")
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang", "clang++")
toolchain_end()
set_toolchains("my_toolchain")
add_includedirs("~/Qt/6.2.4/gcc_64/include")

-- add_frameworks("QtCore")
-- add_frameworks("QtGui")
-- add_frameworks("QtQml")
-- add_frameworks("QtQuick")
add_frameworks("QtQuick3D")
add_frameworks("QtDataVisualization")
add_frameworks("QtSql")
add_frameworks("QtQuickControls2")




-- quickcontrols2

target("chattutorial_chapter5")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/chattutorial/chapter5/qml.qrc")
    add_files("quickcontrols2/chattutorial/chapter5/images/images.qrc")
    add_files("quickcontrols2/chattutorial/chapter5/*.cpp")
    add_files("quickcontrols2/chattutorial/chapter5/*.h")-- add files with Q_OBJECT meta (only for qt.moc)

target("contactlist")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/contactlist/qml.qrc")
    add_files("quickcontrols2/contactlist/*.cpp")
    add_files("quickcontrols2/contactlist/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("flatstyle")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/flatstyle/qml.qrc")
    add_files("quickcontrols2/flatstyle/*.cpp")
    -- add_files("quickcontrols2/flatstyle/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
    add_includedirs("quickcontrols2/flatstyle/imports")
target("gallery")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/gallery/qml.qrc")
    add_files("quickcontrols2/gallery/*.cpp")
    -- add_files("quickcontrols2/custommaterial/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("imagine_automotive")
    add_rules("qt.quickapp")
    -- add_files("quickcontrols2/imagine/automotive/main.qrc")
    add_files("quickcontrols2/imagine/automotive/qml/qml.qrc")
    add_files("quickcontrols2/imagine/automotive/icons/icons.qrc")
    add_files("quickcontrols2/imagine/automotive/imagine-assets/imagine-assets.qrc")
    add_files("quickcontrols2/imagine/automotive/*.cpp")
    -- add_files("quickcontrols2/customshaders/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("imagine_musicplayer")
    add_rules("qt.quickapp")
    -- add_files("quickcontrols2/imagine/automotive/main.qrc")
    add_files("quickcontrols2/imagine/musicplayer/qml.qrc")
    add_files("quickcontrols2/imagine/musicplayer/icons/icons.qrc")
    add_files("quickcontrols2/imagine/musicplayer/imagine-assets/imagine-assets.qrc")
    add_files("quickcontrols2/imagine/musicplayer/*.cpp")
    -- add_files("quickcontrols2/customshaders/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("sidepanel")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/sidepanel/qml.qrc")
    add_files("quickcontrols2/sidepanel/*.cpp")
    -- add_files("quickcontrols2/dynamictexture/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("swipetoremove")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/swipetoremove/qml.qrc")
    add_files("quickcontrols2/swipetoremove/*.cpp")
    -- add_files("quickcontrols2/effects/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("wearable")
    add_rules("qt.quickapp")
    add_files("quickcontrols2/wearable/qml.qrc")
    add_files("quickcontrols2/wearable/*.cpp")
    -- add_files("quickcontrols2/wearable/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
