add_rules("mode.debug", "mode.release")
set_configdir("qt","~/Qt/6.2.4/gcc_64")
toolchain("my_toolchain")
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang", "clang++")
toolchain_end()
set_toolchains("my_toolchain")
add_includedirs("~/Qt/6.2.4/gcc_64/include")

-- add_frameworks("QtCore")
-- add_frameworks("QtGui")
-- add_frameworks("QtQml")
-- add_frameworks("QtQuick")
add_frameworks("QtDataVisualization")

-- datavisualization
target("qmlbars")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlbars/qmlbars.qrc")
    add_files("datavisualization/qmlbars/main.cpp")
target("qml3doscilloscope")
    add_rules("qt.quickapp")
    add_files("datavisualization/qml3doscilloscope/qml3doscilloscope.qrc")
    add_files("datavisualization/qml3doscilloscope/*.cpp")
    add_files("datavisualization/qml3doscilloscope/*.h")-- add files with Q_OBJECT meta (only for qt.moc),not add_includedirs,or add_headerfiles
target("qmlaxisdrag")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlaxisdrag/qmlaxisdrag.qrc")
    add_files("datavisualization/qmlaxisdrag/*.cpp")
target("customformatter")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlaxisformatter/qmlaxisformatter.qrc")
    add_files("datavisualization/qmlaxisformatter/*.cpp")
    add_files("datavisualization/qmlaxisformatter/*.h")
target("customproxy")
    add_rules("qt.quickapp")
    add_files("datavisualization/customproxy/customproxy.qrc")
    add_files("datavisualization/customproxy/*.cpp")
    add_files("datavisualization/customproxy/*.h")
target("qmlcustominput")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlcustominput/qmlcustominput.qrc")
    add_files("datavisualization/qmlcustominput/*.cpp")
    -- add_files("datavisualization/qmlcustominput/*.h")
target("qmllegend")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmllegend/qmllegend.qrc")
    add_files("datavisualization/qmllegend/*.cpp")
    -- add_files("datavisualization/qmllegend/*.h")
target("qmlmultigraph")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlmultigraph/qmlmultigraph.qrc")
    add_files("datavisualization/qmlmultigraph/*.cpp")
    -- add_files("datavisualization/qmlmultigraph/*.h")
target("qmlscatter")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlscatter/qmlscatter.qrc")
    add_files("datavisualization/qmlscatter/*.cpp")
    -- add_files("datavisualization/qmlscatter/*.h")
target("qmlspectrogram")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlspectrogram/qmlspectrogram.qrc")
    add_files("datavisualization/qmlspectrogram/*.cpp")
    -- add_files("datavisualization/qmlspectrogram/*.h")
target("qmlsurface")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlsurface/qmlsurface.qrc")
    add_files("datavisualization/qmlsurface/*.cpp")
    -- add_files("datavisualization/qmlsurface/*.h")
target("qmlsurfacelayers")
    add_rules("qt.quickapp")
    add_files("datavisualization/qmlsurfacelayers/qmlsurfacelayers.qrc")
    add_files("datavisualization/qmlsurfacelayers/*.cpp")
    -- add_files("datavisualization/qmlsurfacelayers/*.h")

    
    

    

