add_rules("mode.debug", "mode.release")
set_configdir("qt","~/Qt/6.2.4/gcc_64")
toolchain("my_toolchain")
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang", "clang++")
toolchain_end()
set_toolchains("my_toolchain")
add_includedirs("~/Qt/6.2.4/gcc_64/include")

-- add_frameworks("QtCore")
-- add_frameworks("QtGui")
-- add_frameworks("QtQml")
-- add_frameworks("QtQuick")
add_frameworks("QtQuick3D")
add_frameworks("QtDataVisualization")


-- quick3d
target("antialiasing")
    add_rules("qt.quickapp")
    add_files("quick3d/antialiasing/qml.qrc")
    add_files("quick3d/antialiasing/*.cpp")
    -- add_files("quick3d/antialiasing/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("customeffect")
    add_rules("qt.quickapp")
    add_files("quick3d/customeffect/qml.qrc")
    add_files("quick3d/customeffect/*.cpp")
    -- add_files("quick3d/customgeometry/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("customgeometry")
    add_rules("qt.quickapp")
    add_files("quick3d/customgeometry/qml.qrc")
    add_files("quick3d/customgeometry/*.cpp")
    add_files("quick3d/customgeometry/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("custommaterial")
    add_rules("qt.quickapp")
    add_files("quick3d/custommaterial/qml.qrc","quick3d/custommaterial/materials.qrc")
    add_files("quick3d/custommaterial/*.cpp")
    -- add_files("quick3d/custommaterial/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("customshaders")
    add_rules("qt.quickapp")
    add_files("quick3d/customshaders/qml.qrc")
    add_files("quick3d/customshaders/*.cpp")
    -- add_files("quick3d/customshaders/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("dynamiccreation")
    add_rules("qt.quickapp")
    add_files("quick3d/dynamiccreation/qml.qrc")
    add_files("quick3d/dynamiccreation/*.cpp")
    -- add_files("quick3d/dynamiccreation/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("dynamictexture")
    add_rules("qt.quickapp")
    add_files("quick3d/dynamictexture/qml.qrc")
    add_files("quick3d/dynamictexture/*.cpp")
    -- add_files("quick3d/dynamictexture/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("effects")
    add_rules("qt.quickapp")
    add_files("quick3d/effects/qml.qrc")
    add_files("quick3d/effects/*.cpp")
    -- add_files("quick3d/effects/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("hellocube")
    add_rules("qt.quickapp")
    add_files("quick3d/hellocube/qml.qrc")
    add_files("quick3d/hellocube/*.cpp")
    -- add_files("quick3d/hellocube/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("instancing")
    add_rules("qt.quickapp")
    add_files("quick3d/instancing/qml.qrc")
    add_files("quick3d/instancing/*.cpp")
    -- add_files("quick3d/instancing/*.h")-- add files with Q_OBJECT meta (only for qt.moc)    
target("intro")
    add_rules("qt.quickapp")
    add_files("quick3d/intro/qml.qrc")
    add_files("quick3d/intro/*.cpp")
    -- add_files("quick3d/intro/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("lights")
    add_rules("qt.quickapp")
    add_files("quick3d/lights/qml.qrc")
    add_files("quick3d/lights/*.cpp")
    -- add_files("quick3d/lights/*.h")-- add files with Q_OBJECT meta (only for qt.moc)    
target("morphing")
    add_rules("qt.quickapp")
    add_files("quick3d/morphing/qml.qrc")
    add_files("quick3d/morphing/*.cpp")
    -- add_files("quick3d/morphing/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("offlineshaders")
    add_rules("qt.quickapp")
    add_files("quick3d/offlineshaders/qml.qrc")
    add_files("quick3d/offlineshaders/*.cpp")
    -- add_files("quick3d/offlineshaders/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("particles3d")
    add_rules("qt.quickapp")
    add_files("quick3d/particles3d/qml.qrc")
    add_files("quick3d/particles3d/*.cpp")
    -- add_files("quick3d/particles3d/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("picking")
    add_rules("qt.quickapp")
    add_files("quick3d/picking/qml.qrc")
    add_files("quick3d/picking/*.cpp")
    -- add_files("quick3d/picking/*.h")-- add files with Q_OBJECT meta (only for qt.moc)
target("principledmaterial")
    add_rules("qt.quickapp")
    add_files("quick3d/principledmaterial/qml.qrc","quick3d/principledmaterial/materials.qrc")
    add_files("quick3d/principledmaterial/*.cpp")
    -- add_files("quick3d/principledmaterial/*.h")-- add files with Q_OBJECT meta (only for qt.moc)    
target("quickball")
    add_rules("qt.quickapp")
    add_files("quick3d/quickball/qml.qrc")
    add_files("quick3d/quickball/*.cpp")
    -- add_files("quick3d/quickball/*.h")-- add files with Q_OBJECT meta (only for qt.moc)      
target("quickitems")
    add_rules("qt.quickapp")
    add_files("quick3d/quickitems/qml.qrc")
    add_files("quick3d/quickitems/*.cpp")
    -- add_files("quick3d/quickitems/*.h")-- add files with Q_OBJECT meta (only for qt.moc)      
target("runtimeloader")
    add_rules("qt.quickapp")
    add_files("quick3d/runtimeloader/qml.qrc")
    add_files("quick3d/runtimeloader/*.cpp")
    -- add_files("quick3d/runtimeloader/*.h")-- add files with Q_OBJECT meta (only for qt.moc)      
target("screenspacereflections")
    add_rules("qt.quickapp")
    add_files("quick3d/screenspacereflections/qml.qrc","quick3d/screenspacereflections/materials.qrc")
    add_files("quick3d/screenspacereflections/*.cpp")
    -- add_files("quick3d/screenspacereflections/*.h")-- add files with Q_OBJECT meta (only for qt.moc)   
target("submeshes")
    add_rules("qt.quickapp")
    add_files("quick3d/submeshes/qml.qrc","quick3d/submeshes/meshes.qrc")
    add_files("quick3d/submeshes/*.cpp")
    -- add_files("quick3d/submeshes/*.h")-- add files with Q_OBJECT meta (only for qt.moc)      
target("view3d")
    add_rules("qt.quickapp")
    add_files("quick3d/view3d/qml.qrc")
    add_files("quick3d/view3d/*.cpp")
    -- add_files("quick3d/view3d/*.h")-- add files with Q_OBJECT meta (only for qt.moc)      

